name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Clone repository and deploy to VM
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          if [ ! -d "/var/www/simple-backend-api" ]; then
            sudo mkdir -p /var/www/simple-backend-api
            git clone https://github.com/nitin1053/backend_apis.git /var/www/simple-backend-api
          fi
          cd /var/www/simple-backend-api
          git pull origin main
          npm install
          PORT=3000 nohup node index.js &

    - name: Verify deployment
      run: curl http://${{ secrets.VM_HOST }}:80/sayHello
